### ISSUE TITLE
Project management board

### ISSUE THREAD

**Issue by SalttySugar** [SalttySugar/yet-another-kanban#4]
## Description

As a user, I need a system to help me manage multiple projects. I require the ability to create personal workspaces that are exclusively mine, each clearly distinguishable from the others. Within these workspaces, I need to organize assignments into groups. These groups must be unique across workspaces for clarity and ease of use.

### Workspace Management

- [ ] Create a workspace
- [ ] Rename a workspace
- [ ] Delete a workspace

### Group Management

- [ ] Create a group
- [ ] Delete a group
- [ ] Rename a group
- [ ] Move a group to another group

### Assignment Management

- [ ] Create an assignment
- [ ] Update an assignment
- [ ] Delete an assignment
- [ ] Move an assignment to another group
- [ ] Reorder assignments within the same group
